name: .NET Core

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build /WpfExtendedControls/WpfExtendedControls.csproj --configuration Release
    - name: Select WPFComponents
      run: cd WPFComponents
    - name: Create package
      run: dotnet pack /WPFComponents --configuration Release
    - name: Publish package
      env:
        AUTH_TOKEN: ${{ secrets.Publish }}
      run: dotnet nuget push /bin/Release
